components_manager:
  task_processors:
    main-task-processor:
      worker_threads: 4
    fs-task-processor:
      worker_threads: 2
  default_task_processor: main-task-processor
  components:
    server:
      listener:
        port: 8081
        task_processor: main-task-processor
    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: info
          overflow_behavior: discard
    handler-health:
      path: /health
      method: GET
      task_processor: main-task-processor
    handler-user-register:
      path: /v1/users
      method: POST
      task_processor: main-task-processor
    handler-auth-login:
      path: /v1/auth/login
      method: POST
      task_processor: main-task-processor
      jwt-secret: dev-jwt-hmac-secret-do-not-use-in-prod
    handler-user-by-login:
      path: /v1/users/by-login/{login}
      method: GET
      task_processor: main-task-processor
    handler-user-search:
      path: /v1/users/search
      method: GET
      task_processor: main-task-processor
    handler-user-internal:
      path: /v1/internal/users/{id}
      method: GET
      task_processor: main-task-processor
